#!/bin/bash

ESCAPE='\033['
LIGHT_BLUE="${ESCAPE}1;34m"
NC='\033[0m' # No Color

loginfo() {
  if [[ -z ${VSCODE_TASK} && -z $JENKINS_URL && "$(uname)" == "Linux" ]]; then
    echo -e "${LIGHT_BLUE}$1${NC}"
  else
    echo $1
  fi 
}

export -f loginfo
