echo ""
echo "================================================================================"
echo "= Solar system info"
echo "================================================================================"
echo ""
echo "⚫ Solar:                              solar_get_status.sh"
echo "⚫ Shunts:                             query_shunts.sh"
echo ""
echo ""
echo "================================================================================"
echo "= Raspberry GPIO/i2c"
echo "================================================================================"
echo ""
echo "⚫ GPIO:                               gpio readall"
echo "⚫ i2c:                                i2cdetect -y 1"
echo ""
echo ""
echo "================================================================================"
echo "= Network utilities"
echo "================================================================================"
echo ""
echo "⚫ nethogs (live)                      sudo nethogs ppp0"
echo "⚫ iptables (traffic since 1AM/PM)     sudo iptables -L -v"
echo "⚫ netstat (open ports)                netstat -tulpn"
echo "⚫ netstat (open ports 2)              netstat --inet -ap"
echo "⚫ logged DROPPED inb. connections     cat /var/log/syslog | grep -E 'INPUT:"
echo ""
echo ""

